-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO products (name, description, price)
-- VALUES
--     ('Banana', 'A tasty yellow fruit with a slight bend', '0.60'),
--     ('Lamborghini', 'A wildly impractical car', '500000'),
--     ('Wooden chair', 'Classic looking yet comfortable', '319.99'),
--     ('OLED TV', 'Very impressive contrast ratio', '1260.50');
